module.exports = {
    username: 'username',
    password: 'password',
    ccnumber: 'ccnumber',
    cvv: 'cvv',
    ccexp : 'ccexp',
    amount: 'amount',
    ipaddress: 'ipaddress',
    orderid: 'orderid',
    orderdescription: 'orderdescription',
    tax: 'tax',
    shipping: 'shipping',
    ponumber: 'ponumber',
    firstname: 'firstname',
    lastname: 'lastname',
    company: 'company',
    address1: 'address1',
    address2: 'address2',
    city: 'city',
    state: 'state',
    zip: 'zip',
    country: 'country',
    phone: 'phone',
    fax: 'fax',
    website: 'website',
    type: 'type'
};